---
<% unless ENV['RAILS_ENV'] == 'production' %>
:logfile: ./log/sidekiq.log
<% end %>
:concurrency: 5
:queues:
  - important
  - default

development:
  :concurrency: 10

test:
  :concurrency: 10

production:
  :concurrency: 25